# Generated by Django 2.2.7 on 2019-11-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191125_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
