# Generated by Django 2.2.7 on 2020-02-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200228_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Entry'),
            preserve_default=False,
        ),
    ]
