# Generated by Django 2.2.7 on 2020-02-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_fileupload_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Entry'),
        ),
    ]
