# Generated by Django 2.2.7 on 2020-03-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200228_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Entry'),
            preserve_default=False,
        ),
    ]
